markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Daria Jung   
production_url : http:dariajung.github.com
description: "catz, code, and a good cup of earl grey"
disqus_shortname: dariajjung      
analytics:
gauges:
author :
  name : Daria Jung 
  github : dariajung
  twitter : djj2115
  email: djj2115cu@gmail.com
